SELECT 
    GET_VEHICLE_CATEGORY_ID(1, 'Economy Car', '', '') = 1 vr_1_1,
    GET_VEHICLE_CATEGORY_ID(1, 'Compact Auto', '', '') = 2 vr_1_2,
    GET_VEHICLE_CATEGORY_ID(1, 'Compact SUV 2WD', '', '') = 3 vr_1_3,
    GET_VEHICLE_CATEGORY_ID(1, 'Intermediate SUV AWD', '', '') = 4 vr_1_4,
    GET_VEHICLE_CATEGORY_ID(1,
            'Fullsize AWD (seats 5-7 passengers)',
            '',
            '') = 5 vr_1_5,
    GET_VEHICLE_CATEGORY_ID(1, 'Passenger Van', '', '') = 6 vr_1_6,
    GET_VEHICLE_CATEGORY_ID(1, 'Utility Vehicle with towbar', '', '') = 7 vr_1_7,
    GET_VEHICLE_CATEGORY_ID(1, 'Intermediate SUV 2WD', '', '') = 8 vr_1_8,
    GET_VEHICLE_CATEGORY_ID(1, 'Luxury Van', '', '') = 9 vr_1_9,
    GET_VEHICLE_CATEGORY_ID(1, 'Electric Vehicle', '', '') = 10 vr_1_10,
    GET_VEHICLE_CATEGORY_ID(2, 'Economy', '', '') = 1 vr_2_1,
    GET_VEHICLE_CATEGORY_ID(2, 'Compact', '', '') = 2 vr_2_2,
    GET_VEHICLE_CATEGORY_ID(2, 'Intermediate', '', '') = 11 vr_2_11,
    GET_VEHICLE_CATEGORY_ID(2, 'Full Size', '', '') = 12 vr_2_12,
    GET_VEHICLE_CATEGORY_ID(2, 'Full Size Elite', '', '') = 13 vr_2_13,
    GET_VEHICLE_CATEGORY_ID(2, 'Compact SUV', '', '') = 3 vr_2_3,
    GET_VEHICLE_CATEGORY_ID(2, 'Intermediate SUV', '', '') = 4 vr_2_4,
    GET_VEHICLE_CATEGORY_ID(2, 'Full Size Hybrid', '', '') = 14 vr_2_14,
    GET_VEHICLE_CATEGORY_ID(2, 'Full Size SUV', '', '') = 5 vr_2_5,
    GET_VEHICLE_CATEGORY_ID(2, 'Premium SUV', '', '') = 15 vr_2_15,
    GET_VEHICLE_CATEGORY_ID(2, 'Premium Ute', '', '') = 7 vr_2_7,
    GET_VEHICLE_CATEGORY_ID(2, 'Premium Minivan', '', '') = 9 vr_2_9,
    GET_VEHICLE_CATEGORY_ID(2, 'Compact Hybrid', '', '') = 23 vr_2_23,
    GET_VEHICLE_CATEGORY_ID(2, 'Standard SUV', '', '') = 8 vr_2_8,
    GET_VEHICLE_CATEGORY_ID(3,
            'Small Cars',
            'Toyota Yaris or similar',
            '1 year(s) old') = 1 vr_3_1,
    GET_VEHICLE_CATEGORY_ID(3,
            'Small Cars',
            'Toyota Corolla Hatch',
            '1 - 2 year(s) old') = 2 vr_3_2,
    GET_VEHICLE_CATEGORY_ID(3,
            'Small Cars',
            'Toyota CHR or similar',
            '1 year(s) old') = 3 vr_3_3,
    GET_VEHICLE_CATEGORY_ID(3,
            'Small Cars',
            'Toyota Corolla Hatch',
            '3 year(s) old') = 16 vr_3_16,
    GET_VEHICLE_CATEGORY_ID(3,
            'Small Cars',
            'Toyota Corolla Hatch',
            '4 - 5 year(s) old') = 17 vr_3_17,
    GET_VEHICLE_CATEGORY_ID(3,
            'Large Cars / SUVs',
            'Toyota Corolla Sedan',
            '5 year(s) old') = 18 vr_3_18,
    GET_VEHICLE_CATEGORY_ID(3,
            'Large Cars / SUVs',
            'Toyota Corolla Sedan',
            '2 - 3 year(s) old') = 19 vr_3_19,
    GET_VEHICLE_CATEGORY_ID(3,
            'Large Cars / SUVs',
            'Hyundai Tucson or similar',
            '1 year(s) old') = 3 vr_3_3,
    GET_VEHICLE_CATEGORY_ID(3,
            'Large Cars / SUVs',
            'Toyota Camry Hybrid',
            '4 - 5 year(s) old') = 14 vr_3_14,
    GET_VEHICLE_CATEGORY_ID(3,
            '4 Wheel Drives',
            'Toyota Rav4 AWD or similar',
            '2 - 3 year(s) old') = 4 vr_3_4,
    GET_VEHICLE_CATEGORY_ID(3,
            '4 Wheel Drives',
            'Mitsubishi Pajero Sport',
            '0 year(s) old') = 5 vr_3_5,
    GET_VEHICLE_CATEGORY_ID(3,
            '4 Wheel Drives',
            'Toyota Land Cruiser Prado',
            '1 year(s) old') = 15 vr_3_15,
    GET_VEHICLE_CATEGORY_ID(3,
            '4 Wheel Drives',
            'Toyota Hilux SR5 4X4',
            '1 year(s) old') = 7 vr_3_7,
    GET_VEHICLE_CATEGORY_ID(3,
            'Van or People Carriers',
            'Hyundai iMax',
            '1 - 2 year(s) old') = 9 vr_3_9,
    GET_VEHICLE_CATEGORY_ID(3,
            'Van or People Carriers',
            'Toyota Hiace (10 Seater)',
            '2 - 4 year(s) old') = 20 vr_3_20,
    GET_VEHICLE_CATEGORY_ID(3,
            'Van or People Carriers',
            'Toyota Hiace (12 Seater)',
            '2 - 5 year(s) old') = 6 vr_3_6,
    GET_VEHICLE_CATEGORY_ID(3,
            'Van or People Carriers',
            'Luggage Trailer',
            '5 - 12 year(s) old') = 21 vr_3_21,
    GET_VEHICLE_CATEGORY_ID(3,
            'Manual Cars',
            'Toyota Corolla Manual',
            '5 year(s) old') = 22 vr_3_22;
